title: FLoCs
description: Containers for LOFAR data reduction with a focus on imaging science.
remote_theme: just-the-docs/just-the-docs

url: https://tikk3r.github.io/lofar-grid-hpccloud/


callouts:
  warning:
    title: Warning
    color: red
  important:
    title: Important
    color: blue

aux_links:
  Recipes on GitHub: https://github.com/tikk3r/lofar-grid-hpccloud
